name: MonsterSyLa Cron

on:
  schedule:
    - cron: '0 23 * * 0'
    - cron: '0 12 * * 1'

  workflow_dispatch:
    inputs:
      modo:
        description: 'domingo o lunes'
        required: true
        default: 'domingo'

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      CR_API_KEY: ${{ secrets.CR_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Auto Domingo
        if: github.event.schedule == '0 23 * * 0'
        run: node scripts/syncClans.js domingo

      - name: Auto Lunes
        if: github.event.schedule == '0 12 * * 1'
        run: node scripts/syncClans.js lunes

      - name: Manual
        if: github.event_name == 'workflow_dispatch'
        run: node scripts/syncClans.js ${{ github.event.inputs.modo }}
